import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/header";

// import menuSection from "@/components/menuSection";
import "./globals.css";
import MenuSection from "@/components/menuSection";
import FooterPage from "@/components/footerPage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <header className=" bg-[#253B8E] pt-4 items-center w-full flex justify-center">
            <Header />
          </header>
            <div className="w-full sticky top-[0px] z-50 bg-[#253B8E] flex justify-center pt-9 pb-7">
    <MenuSection />
  </div>
        <main className="pb-[80px]">
       


   


          {children}
          </main>
          <footer className="w-full flex flex-col items-center pt-8">
            <div className="h-[1px] w-full bg-[#eeeeee] relative top-[80px] -z-1"></div>
            <FooterPage/>
            <div className="w-full">
              <p className="text-center text-white bg-[#1c3377] py-4">تمامی حقوق وبسایت آریا تجارت برای شرکت آریا تجارت محفوظ میباشد.</p>
            </div>
            </footer>
   
      </body>
    </html>
  );
}
